### ISSUE TITLE
Question about Subscriber options

### ISSUE THREAD

**Issue by hummerpj** [jkruer01/EasyRedisMQ#2]
First off this looks pretty great, thanks for sharing!

I had a quick question about the 2 possible patterns for the subscribers (each w/ unique id vs. one shared id).

In my scenario I will have 1 exchange, 3 publishers and 3 subscribers.  I wanted to make sure that the 3 subscribers do not duplicate any work and it sounds like using one shared id would make this happen.  In the documentation you mention `message will be delivered on a first come first serve basis`.  Does this mean that only one of the subscribers will receive any given message, even though each of them is notified?

**Comment by jkruer01** [comment]
Each unique subscriber ID gets its own message queue for the exchange that it is subscribed to.  There are two scenarios where I see this being used.

**Scenario 1: Load Balancing/Redundancy of Multiple Subscribers**
NEED: When Message A is published I need multiple subscribers to process the queue for load balancing and/or redundancy purposes.

If all 3 subscribers use the same subscriber ID then there will only be one message queue.  If subscriber 1 pulls message A off of that message queue then message A will no longer exist in that message queue so subscriber 2 and subscriber 3 will not receive it.  

If too many messages are published for a single subscriber to handle them then this method would allow additional subscribers to be added to share the work load.

In addition, by having multiple subscribers to the same message queue, then if one subscriber crashes then the other subscribers would still be available to process messages on that queue.

**Scenario 2: Multiple Unrelated Subscribers**
NEED: When Message A is published I need multiple subscribers to perform multiple unrelated tasks simultaneously.

For example, when Message A is published I need Event 1 (Send an Email), Event 2 (Insert a Record into the Database), and Event 3 (Make an API Call) to all happen.  These events are not dependent on each other and their order of completion is not important.

If each subscriber uses a unique subscriber ID then when message A is published a separate copy will go to each of the 3 message queues (one for each unique subscriber ID).  Then each of the 3 subscribers would each receive their own copy of message A.

Of course, these 2 scenarios could also be combined so that you have 3 Event 1 Subscribers (all with the same subscriber ID), 3 Event 2 Subscribers (all with the same subscriber ID), and 3 Event 3 Subscribers (all with the same subscriber ID).  This would add the load balancing and redundancy to scenario 2.

I hope this helps to answer your question.  Please let me know if you have any other questions.

**Comment by hummerpj** [comment]
Thanks for the quick reply.  Scenario 1 is exactly what I was referring to.  Just was making sure that even though each subscriber is notified, only one of them grabs the actual message, which sounds like that is the case.

Thanks again!

**Comment by jkruer01** [comment]
As to your question about the 

> message will be delivered on a first come first serve basis

let me explain that a little bit better.

Assume that I have 3 subscribers all with the same subscriber ID.  This means that there is only a single message queue for the messages.  The Message A is published and saved in that message queue.  Then I use redis to notify all 3 subscribers that a new message has been published.  

When a subscriber is notified that a new message has been published it will go into a loop requesting messages one at a time and processing it before requesting another message.  This loop will continue until there are no more messages to process.

The reason that I say it is first come first serve is because I cannot guarantee which of the 3 subscribers will get to the message first. 

Thanks for the question and good luck with your project.
